Jinja formatting issues
djlint/djLint pull request #715
Opened 2023-07-15 23:35 UTC by jlw4049

# Pull Request Check List

Resolves: #issue-number-here

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2023-07-16 09:04 UTC, jlw4049 commented
Note: This forces double quotes on the outside and single quotes inside.

2023-07-16 22:03 UTC, jlw4049 commented
Update, Update new code is stable, passes all tests, allows the linter to detect the outer most quotes and apply changes to the inner most to prevent vscode and syntax errors as well as handles spacing issues that can be caused by using the built in formatter in vscode and then using djlint

2023-07-17 14:22 UTC, christopherpickering requested changes
Thanks for this, I appreciate it. I put a few comments > if you don't want to invest more time you can leave as is and I can pick it up sometime.

2023-07-17 14:22 UTC, christopherpickering commented on tests/test_jinja/test_parenthesis.py
Cool, instead of changing the test here, can you just do 2 tests?

2023-07-17 14:22 UTC, christopherpickering commented on src/djlint/formatter/indent.py
Nunjucks is pretty much identical to jinja, and anyone else using quotes can benefit from this :) Do you mind to remove the the profile check?

![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/ce3c7126-5bc0-43c9-af31-6a79dc36e34e)

aren't cases like this still going to confuse vs code?

The other odd case is where there is a line break:

![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/8e9686e6-e31e-4495-9710-a9c805ac4d44)

I think if we move this down to where we do the set tag formatting, it will be able to work w/ wrapping.

At the same time it might be good to add a flag --single-quote-templatetags, vs a --single-quote tag we can add later on for just html attributes.

Thanks for starting this, if you don't wanna invest more time you can leave as is and I can pick it up sometime.

2023-07-18 05:00 UTC, jlw4049 commented on src/djlint/formatter/indent.py
I can take a look at it to see if I can improve it further in the ways you suggested. 

Specifically by `set tag formatting` are you referring to?
![image](https://github.com/Riverside-Healthcare/djLint/assets/48299282/ee110692-ae6d-4e05-b5ba-0d5d6c3b8726)

In reference to this photo
![image](https://github.com/Riverside-Healthcare/djLint/assets/48299282/5ac352cf-3051-4ede-81ae-9547da7512a1)
I'm not 100% how we could remedy this yet.

I'll think on some things and take a look at this tomorrow.

2023-07-18 05:05 UTC, jlw4049 commented on src/djlint/formatter/indent.py
Ah you must be referring to for the set tag
![image](https://github.com/Riverside-Healthcare/djLint/assets/48299282/7f6e570f-f39d-4212-a473-4b001cac32e0)

I'll look into this and see if I can improve it further. 

As far as the linter for 
`<a href='{{ url("fo\"o") }}'></a>` 
what would you suggest to improve this?

2023-07-18 11:17 UTC, christopherpickering commented on src/djlint/formatter/indent.py
Hey sorry for the delay, yep I think this is the place- it is where the contents of functions are updated.

I'm free to discord call early afternoon today if it's good for you.

2023-07-18 20:26 UTC, jlw4049 commented on src/djlint/formatter/indent.py
Feel free to add me on discord `jlw_4049` so we can talk quicker

2023-09-01 12:03 UTC, christopherpickering commented
Sorry for the delay here. I updated the test case a bit, and added a more complex test. Can every see if they agree w/ this code:

- if outer quote is a double, the first set of inner should be a singe. Lines 1-4 didn't make this change
- notice line 3 and 4 lost a backslash in a string... it should not have been dropped
- this should probably be a config action, I see issues coming up w/ folks who disagree (at the same time remove the jinja restriction)

![image](https://github.com/Riverside-Healthcare/djLint/assets/17788706/5f39d2b2-14c8-4285-962a-dc5fbff62bb0)

2024-02-12 19:12 UTC, jlw4049 commented
> Sorry for the delay here. I updated the test case a bit, and added a more complex test. Can every see if they agree w/ this code:
> 
> * if outer quote is a double, the first set of inner should be a singe. Lines 1-4 didn't make this change
> * notice line 3 and 4 lost a backslash in a string... it should not have been dropped
> * this should probably be a config action, I see issues coming up w/ folks who disagree (at the same time remove the jinja restriction)
> 
> ![image](https://private-user-images.githubusercontent.com/17788706/265014362-5f39d2b2-14c8-4285-962a-dc5fbff62bb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NjI0NDUsIm5iZiI6MTcwNzc2MjE0NSwicGF0aCI6Ii8xNzc4ODcwNi8yNjUwMTQzNjItNWYzOWQyYjItMTRjOC00Mjg1LTk2MmEtZGM1ZmJmZjYyYmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDE4MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNTFmZjUxNzYwNGFiOGUyN2I3ZmZlZjJiMmUxYzI1MDZkMjU0MzA0OTg1NWIzOGJmYmIxMWJiYThhYjE4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pkzlhELo4BoFEFGH_RurBXx3p6pllr7KWYUb12GUF90)

Not really sure how we could remedy this. VSCode is still going to complain about the `expected` test output. 

Not really sure what the best approach would be to remedy this since VSCode doesn't like the expected results either. 
![image](https://github.com/djlint/djLint/assets/48299282/12d8086d-aeed-49e1-9691-c34785a98e13)

2024-08-24 15:12 UTC, dakixr commented
Hey, just checking what is missing here before merging? 

I am using the ident.py changes locally and seems to be working just fine

2024-08-25 02:04 UTC, jessielw commented
The post I made above yours is the last I messed with it. The repository owner isn't maintaining it right now to my understanding. There is @monosans I believe but haven't heard anything on this subject from him. Perhaps he could shed some light on a solution to this.

2024-08-28 13:10 UTC, merged

2024-08-28 13:14 UTC, christopherpickering commented
:tada: This PR is included in version 1.34.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/djlint/v/1.34.2)
- [GitHub release](https://github.com/djlint/djLint/releases/tag/v1.34.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-08-29 12:51 UTC, dakixr commented
Hi @christopherpickering, I just updated the package to the latest release, tks for you incredible work!

However this formatting issue is still present.

Just as an example:

code:
```html
<link rel="stylesheet" href="{{ static('css/output.css') }}?{{ now() .strftime('%d-%m-%Y') }}" />
```

gets formatted into:
```html
<link rel="stylesheet" href="{{ static("css/output.css") }}?{{ now().strftime('%d-%m-%Y') }}" />
```
____

As a workaround I am manually changing ident.py with https://github.com/jessielw/djLint/blob/7b7e504de721e51cf4c5dcc8115540145a8eac23/src/djlint/formatter/indent.py
contents.

Is there any reason why this changes were not included in the new releases?

2024-08-29 12:56 UTC, monosans commented
> Hi @christopherpickering, I just updated the package to the latest release, tks for your incredible work!
> 
> However this formatting issue is still present.
> 
> Just as an example:
> 
> code:
> 
> ```
> <link rel="stylesheet" href="{{ static('css/output.css') }}?{{ now() .strftime('%d-%m-%Y') }}" />
> ```
> 
> gets formatted into:
> 
> ```
> <link rel="stylesheet" href="{{ static("css/output.css") }}?{{ now().strftime('%d-%m-%Y') }}" />
> ```
> 
> As a workaround I am manually changing ident.py with [jessielw/djLint@`7b7e504`/src/djlint/formatter/indent.py](https://github.com/jessielw/djLint/blob/7b7e504de721e51cf4c5dcc8115540145a8eac23/src/djlint/formatter/indent.py) contents.
> 
> Is there any reason why this changes were not included in the new releases?

Seems like I've merged branches incorrectly. Will take a look right now. FYI Christopher is not maintaining djLint anymore.

2024-08-29 13:03 UTC, dakixr commented
> > Hi @christopherpickering, I just updated the package to the latest release, tks for your incredible work!
> > However this formatting issue is still present.
> > Just as an example:
> > code:
> > ```
> > <link rel="stylesheet" href="{{ static('css/output.css') }}?{{ now() .strftime('%d-%m-%Y') }}" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gets formatted into:
> > ```
> > <link rel="stylesheet" href="{{ static("css/output.css") }}?{{ now().strftime('%d-%m-%Y') }}" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As a workaround I am manually changing ident.py with [jessielw/djLint@`7b7e504`/src/djlint/formatter/indent.py](https://github.com/jessielw/djLint/blob/7b7e504de721e51cf4c5dcc8115540145a8eac23/src/djlint/formatter/indent.py) contents.
> > Is there any reason why this changes were not included in the new releases?
> 
> Seems like I've merged branches incorrectly. Will take a look right now. FYI Christopher is not maintaining djLint anymore.

Oh so I will rephrase then, tks you @monosans for your work!

Got it!

2024-08-29 13:28 UTC, monosans commented
I'm pretty sure I've merged everything correctly. Need to find the reason why it doesn't work.

2024-08-29 13:45 UTC, dakixr commented
The issue is with the commit: "- Add the ability to detect what ever the outer most quotes was for e…"

That one re-introduced the bug.

I am using this script to fix it locally for the new releases:

```sh
#!/bin/bash

# URL to fetch the new contents from
# Commit: WORKING - "- Added some regex to ensure we have double quoted attributes for the…"
URL="https://raw.githubusercontent.com/jessielw/djLint/7b7e504de721e51cf4c5dcc8115540145a8eac23/src/djlint/formatter/indent.py"
# Commit: BROKEN - "- Add the ability to detect what ever the outer most quotes was for e…"
# URL="https://raw.githubusercontent.com/jessielw/djLint/e9dc2aaf7c977def61af6c75fd0b7fc87634d198/src/djlint/formatter/indent.py"

# Find all indent.py files under **/djlint/formatter/ directories
files=$(find . -type f -path "*/djlint/formatter/indent.py")

# Loop over each found file and replace its contents
for file in $files; 
do
    echo "Replacing contents of $file"
    curl -s $URL -o "$file"
done

echo "Replacement complete."
```