Performance Improvement 5 - Cache compiled regexes
djlint/djLint pull request #995
Opened 2024-11-01 14:48 UTC by JCWasmx86

Even though the regex module has a cache, it's access is not that fast. E.g. re.sub is a combination of re._compile and pattern.sub. re._compile is checking the flags for e.g. DEBUG values or the verbosity. It uses an enum for the flags. enum.__and__ is quite slow, so even for a cache hit we have around two to three enum.__and__ calls. This patch caches commonly used regexes. The naming probably has to be adjusted.

Commonly used is defined as: pattern._compile is hit with this pattern+flags combination more than 1000 times in the netbox repo. That somewhat balances out the time needed for compilation, the runtime speed and the maintenance effort.

Before:
![image](https://github.com/user-attachments/assets/b9d713b9-e91f-4678-be50-9e0ba896716a)

regex._compile is called 392.678x times, taking 40% of the time
enum.__and__ is called 1.038.531x times, taking 20% of the time

After:

![image](https://github.com/user-attachments/assets/df17edb4-637d-4169-93ae-7c616b5897a5)

regex._compile is called 7226x times, taking 20% of the time
enum.__and__ is called 267.691x times, taking 8-9% of the time. (That's still a lot)

This can probably improved for more regexes, but I think it's somewhat balanced at the point. The compilation time on my PC for the regexes is at around 0.1s

Timings:
Netbox, parallel: 2.5-2.8s
EDX Platform, parallel: 19s

This is the final patch of the performance improvement patch series. There are probably more improvements, but they are not that low-hanging fruits like the last 6 patches.

2024-11-01 15:01 UTC, JCWasmx86 commented on djlint/settings.py
> +        # TODO: How to call it?
I tried to find good names, but these names probably need a bit of help

2024-11-02 13:45 UTC, oliverhaas commented
Hi. I came here mainly to apologize that I broke your branch with my PR. Sorry for that!
I appreciate the work you've put into djlint in your last PRs; I just ran some quick tests earlier and you got some really good numbers out of djlint!

I'm not sure if I understand all the changes, but I naively thought that your approach seems a little bit complicated, and I was gonna suggest to just use lru_cache (with what I assumed was a small performance penalty), basically like this:

```python

# Call this module something like `regex.py` or `regex_custom_wrappers.py` 

import re
from functools import lru_cache


def search(regex, text, use_cache: bool = True, flags=None, **kwargs):
    if use_cache:
        re_compiled = _compile_cached(regex, flags=flags)
        return re_compiled.search(text, **kwargs)
    return re.search(regex, text, flags=flags, **kwargs)

# ... more regex functions

@lru_cache(maxsize=256)
def _compile_cached(regex, flags=None) -> re.Pattern:
    return re.compile(regex, flags=flags)
```

and then it's basically just find & replace. I've got about 20% faster formatting, I think, but I didn't want to spend too much time before I check in with you.
Do you think your approach is worth explicitly storing the compiled regexes?

2024-11-02 19:17 UTC, oliverhaas commented
Can you maybe check two things (if you're interested):

1. What the timing is if you remove the lru_cache. I'm currently seeing that as long as you call .compile() the speed up is the same. I assume that the internal cache of regex (and plain re module also) works well enough in that case.
2. What the timing is if you use plain `re` module instead of `regex`. On my machine it seems to be 20% faster than regex.

2024-11-02 20:00 UTC, oliverhaas commented
(Ignore my previous comment if you had seen it)

Here some stuff I've tried (average of 10 runs reformatting edx-platform):

- Current master: 7.80s
- This PR: 5.81s
- Use `re` module instead of `regex`: 4.89s
- Remove "our" manual caching/`@cache`: 4.90s
- Revert using `.compile()` and just let `re` do the job: 4.75s

So as far as I can see it would probably the best to use `re` and revert most of the manual caching, but let me know if I missed something or if you see different behavior. I would be happy to take care of a PR as well :).

2024-11-03 06:26 UTC, oliverhaas commented
Weird, I did not get an error, but I only reformatted the edx-platform repo on one system and haven't tested anything else.

For me it's hard to keep track of whether `regex` is really still the "new stuff", or whether the important stuff got ported to `re`, especially since both have existed for so long and are (basically?) fully compatible.

**From me it's definitely a thumbs up for merging.**

(Off-topic: I just got a 16-core/32-threads CPU for my old retired workstation for fairly cheap. Haven't benchmarked djlint specifically, but compiling or running tests is literally more than 4 times faster compared to my 4-core laptop, which actually is noticeably making my workflows easier.)

2024-11-03 07:35 UTC, monosans commented
We will not replace `regex` with `re`, as `re` lacks some of the features of `regex` and this would be a breaking change for those who create their own rules in `djlint_rules.yaml`.

2024-11-05 16:55 UTC, monosans commented
Hey, @JCWasmx86! There are some conflicts because of the changes I've made, sorry. Could you please resolve them and do some profiling to see how much this PR improves the performance now? Thanks!

2024-11-07 06:01 UTC, monosans commented
> Hey @monosans, what is needed for this PR to get merged? Can I assist in any kind?

Please see review comments

2024-11-07 12:35 UTC, monosans requested changes

2024-11-07 12:35 UTC, monosans commented on djlint/helpers.py
> +    return [(x.start(0), x.end()) for x in iters]
Let's use tuple here after all. I know that creating a list is faster than tuple, but for a cache we need immutability and memory efficiency.

2024-11-07 12:35 UTC, monosans commented on djlint/regex_utils.py
> +    return re.compile(pattern, flags=flags, cache_pattern=False)
I've disabled caching here since we're already caching it on our end

2024-11-07 12:35 UTC, monosans commented on djlint/helpers.py
> +            break
Could you please explain why this was added? In my tests it didn't give any performance improvements.

2024-11-07 12:35 UTC, monosans commented on djlint/lint.py
> +    ]
Same here

2024-11-07 16:48 UTC, JCWasmx86 commented on djlint/helpers.py
> +            break
The savings are minimal (Average over 4 runs): from 4.95s to  4.85s But I will revert this change

2024-11-07 16:53 UTC, JCWasmx86 commented on djlint/lint.py
> +    ]
Last time I profiled, the cache in `overlaps_ignored_block` made the results worse for some reason. Just caching in lint.py made it faster. Reverted

2024-11-07 17:32 UTC, JCWasmx86 commented on djlint/lint.py
> +            build_flags.cache_clear()
Just one quick question, why was this added? `flags` are just constants so the cache shouldn't grow that big

2024-11-09 21:25 UTC, oliverhaas commented
@JCWasmx86 Thanks again for the hard work. I'm at 1.2s for edx-platform with this branch on my desktop, which is crazy to think about where djlint was just a while ago. I basically only have one feature/bug left on my pain points, and just a month ago I was looking for alternatives to djlint...

If you could share your profiling script in a gist or something, that would be awesome. I can't seem to get the profiler output quite as readable as your images.

2024-11-10 14:00 UTC, JCWasmx86 commented on djlint/helpers.py
> +    return [(x.start(0), x.end()) for x in iters]
You marked this as resolved. So, is this relevant or should I really convert this to a tuple?

2024-12-31 10:39 UTC, JCWasmx86 commented on djlint/lint.py
> +            build_flags.cache_clear()
@monosans Could you please check this comment? Furthermore I've rebased the this PR

2025-02-23 18:41 UTC, closed without merging